name: Lighthouse CI
on:
  pull_request:
    types: [opened, reopened]

jobs:
  lhci:
    name: Lighthouse
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js LTS
        uses: actions/setup-node@v3
        with:
          node-version: "lts/*"
      - name: npm install, build
        run: |
          npm install
          npm run build
      - name: Connect next server & run Lighthouse CI
        run: |
          npm install -g @lhci/cli@0.12.x
          lhci autorun --collect.url=https://tv.dmm.com/vod/ --upload.target=temporary-public-storage --staticDistDir=./build
